// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCQaa2iX962MUw8hc8hNeku0yLi6opsBXA',
    appId: '1:583408858703:web:3d4707a00c0e5a62281c3a',
    messagingSenderId: '583408858703',
    projectId: 'date-guide-ede17',
    authDomain: 'date-guide-ede17.firebaseapp.com',
    storageBucket: 'date-guide-ede17.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDBfys-5h_OCSzhnKclm3AasWYKkx8TTrQ',
    appId: '1:583408858703:android:66d1a8a26544eadd281c3a',
    messagingSenderId: '583408858703',
    projectId: 'date-guide-ede17',
    storageBucket: 'date-guide-ede17.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBnOrCyvsFBt06aS3A02GPcy6o00i95g0o',
    appId: '1:583408858703:ios:2785c8a363d60753281c3a',
    messagingSenderId: '583408858703',
    projectId: 'date-guide-ede17',
    storageBucket: 'date-guide-ede17.firebasestorage.app',
    iosBundleId: 'com.date.dateGuide',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBnOrCyvsFBt06aS3A02GPcy6o00i95g0o',
    appId: '1:583408858703:ios:2785c8a363d60753281c3a',
    messagingSenderId: '583408858703',
    projectId: 'date-guide-ede17',
    storageBucket: 'date-guide-ede17.firebasestorage.app',
    iosBundleId: 'com.date.dateGuide',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCQaa2iX962MUw8hc8hNeku0yLi6opsBXA',
    appId: '1:583408858703:web:b55c20bfda5ce4cf281c3a',
    messagingSenderId: '583408858703',
    projectId: 'date-guide-ede17',
    authDomain: 'date-guide-ede17.firebaseapp.com',
    storageBucket: 'date-guide-ede17.firebasestorage.app',
  );
}
